### ISSUE TITLE
MQTT both ways?

### ISSUE THREAD

**Issue by Cloolalang** [PuceBaboon/ESP-Now-Gateway#2]
I really like this project, one question:
can the node/gateway subscribe to mqtt topics on a broker thus the system being two way?
P

**Comment by PuceBaboon** [comment]
Cloolaang,

   Glad to hear you're finding it useful.

   I haven't actually done this myself, but there's a whole, detailed section in the mosquitto.conf manual page about setting up a bridge between mulitple mqtt brokers.  Another option worth looking at is the mosquitto_rr (request/response) client.  It's also a part of the standard mosquitto distribution and allows you to do things like hold connections open and send from stdio or files.

   As it stands at the moment, there's no reason why the gateway shouldn't be able to subscribe to topics from another broker, but the bridge or R/R options may make it easier to offload certain tasks onto another, more powerful machine on your network.

   Let us know how it goes,

                             -John-
